// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: opts/page.proto

package opts

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Opts) Validate() error {
	return nil
}
func (this *Page) Validate() error {
	return nil
}
func (this *SkipLimit) Validate() error {
	return nil
}
