// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user/user.proto

package user

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ModifyRightsRequest) Validate() error {
	if this.BanReview != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.BanReview); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("BanReview", err)
		}
	}
	return nil
}
func (this *ShortUsers) Validate() error {
	for _, item := range this.Users {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Users", err)
			}
		}
	}
	return nil
}
func (this *ShortUser) Validate() error {
	return nil
}
func (this *SignUpUser) Validate() error {
	return nil
}
func (this *GetByIdRequest) Validate() error {
	return nil
}
func (this *GetByIdsRequest) Validate() error {
	return nil
}
func (this *AuthRequest) Validate() error {
	return nil
}
func (this *MicrosoftAuthRequest) Validate() error {
	return nil
}
func (this *YahooAuthRequest) Validate() error {
	return nil
}
func (this *FacebookAuthRequest) Validate() error {
	return nil
}
func (this *AppleAuthRequest) Validate() error {
	return nil
}
func (this *GoogleAuthRequest) Validate() error {
	return nil
}
func (this *SelfUser) Validate() error {
	return nil
}
