// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: authentication/authentication.proto

package auth

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ValidationBearerTokenRequest) Validate() error {
	return nil
}
func (this *DispatchAuthCommandRequest) Validate() error {
	return nil
}
