// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/authentication.proto

package auth

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ValidationBearerTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ValidationBearerTokenRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Token

	return nil
}

// ValidationBearerTokenRequestValidationError is the validation error returned
// by ValidationBearerTokenRequest.Validate if the designated constraints
// aren't met.
type ValidationBearerTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidationBearerTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidationBearerTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidationBearerTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidationBearerTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidationBearerTokenRequestValidationError) ErrorName() string {
	return "ValidationBearerTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ValidationBearerTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidationBearerTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidationBearerTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidationBearerTokenRequestValidationError{}

// Validate checks the field values on DispatchAuthCommandRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DispatchAuthCommandRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	// no validation rules for Payload

	return nil
}

// DispatchAuthCommandRequestValidationError is the validation error returned
// by DispatchAuthCommandRequest.Validate if the designated constraints aren't met.
type DispatchAuthCommandRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DispatchAuthCommandRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DispatchAuthCommandRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DispatchAuthCommandRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DispatchAuthCommandRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DispatchAuthCommandRequestValidationError) ErrorName() string {
	return "DispatchAuthCommandRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DispatchAuthCommandRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDispatchAuthCommandRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DispatchAuthCommandRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DispatchAuthCommandRequestValidationError{}

// Validate checks the field values on TokenValidationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *TokenValidationResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Token

	// no validation rules for Success

	return nil
}

// TokenValidationResponseValidationError is the validation error returned by
// TokenValidationResponse.Validate if the designated constraints aren't met.
type TokenValidationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TokenValidationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TokenValidationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TokenValidationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TokenValidationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TokenValidationResponseValidationError) ErrorName() string {
	return "TokenValidationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TokenValidationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTokenValidationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TokenValidationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TokenValidationResponseValidationError{}
