// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package business

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BusinessClient is the client API for Business service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BusinessClient interface {
	ApplyBusinessOwner(ctx context.Context, in *ApplyBusinessOwnerRequest, opts ...grpc.CallOption) (*ApplyBusinessOwnerResponse, error)
	VerifyBusinessOwner(ctx context.Context, in *VerifyBusinessOwnerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// only owner can set admins (up to 50)
	AddBusinessAdmin(ctx context.Context, in *AddBusinessAdminRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveBusinessAdmin(ctx context.Context, in *RemoveBusinessAdminRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// company owner can move self owner-role to another user. this action is irreversible
	SetCompanyOwner(ctx context.Context, in *SetBusinessOwnerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetManagers(ctx context.Context, in *GetManagersRequest, opts ...grpc.CallOption) (*GetManagersResponse, error)
	CanEditBusiness(ctx context.Context, in *CanEditBusinessRequest, opts ...grpc.CallOption) (*CanEditBusinessResponse, error)
	// where current user is owner or admin
	GetOwnBusinesses(ctx context.Context, in *GetOwnBusinessesRequest, opts ...grpc.CallOption) (*GetOwnBusinessesResponse, error)
}

type businessClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessClient(cc grpc.ClientConnInterface) BusinessClient {
	return &businessClient{cc}
}

func (c *businessClient) ApplyBusinessOwner(ctx context.Context, in *ApplyBusinessOwnerRequest, opts ...grpc.CallOption) (*ApplyBusinessOwnerResponse, error) {
	out := new(ApplyBusinessOwnerResponse)
	err := c.cc.Invoke(ctx, "/business.Business/ApplyBusinessOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) VerifyBusinessOwner(ctx context.Context, in *VerifyBusinessOwnerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/business.Business/VerifyBusinessOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddBusinessAdmin(ctx context.Context, in *AddBusinessAdminRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/business.Business/AddBusinessAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) RemoveBusinessAdmin(ctx context.Context, in *RemoveBusinessAdminRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/business.Business/RemoveBusinessAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) SetCompanyOwner(ctx context.Context, in *SetBusinessOwnerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/business.Business/SetCompanyOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetManagers(ctx context.Context, in *GetManagersRequest, opts ...grpc.CallOption) (*GetManagersResponse, error) {
	out := new(GetManagersResponse)
	err := c.cc.Invoke(ctx, "/business.Business/GetManagers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) CanEditBusiness(ctx context.Context, in *CanEditBusinessRequest, opts ...grpc.CallOption) (*CanEditBusinessResponse, error) {
	out := new(CanEditBusinessResponse)
	err := c.cc.Invoke(ctx, "/business.Business/CanEditBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetOwnBusinesses(ctx context.Context, in *GetOwnBusinessesRequest, opts ...grpc.CallOption) (*GetOwnBusinessesResponse, error) {
	out := new(GetOwnBusinessesResponse)
	err := c.cc.Invoke(ctx, "/business.Business/GetOwnBusinesses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessServer is the server API for Business service.
// All implementations must embed UnimplementedBusinessServer
// for forward compatibility
type BusinessServer interface {
	ApplyBusinessOwner(context.Context, *ApplyBusinessOwnerRequest) (*ApplyBusinessOwnerResponse, error)
	VerifyBusinessOwner(context.Context, *VerifyBusinessOwnerRequest) (*emptypb.Empty, error)
	// only owner can set admins (up to 50)
	AddBusinessAdmin(context.Context, *AddBusinessAdminRequest) (*emptypb.Empty, error)
	RemoveBusinessAdmin(context.Context, *RemoveBusinessAdminRequest) (*emptypb.Empty, error)
	// company owner can move self owner-role to another user. this action is irreversible
	SetCompanyOwner(context.Context, *SetBusinessOwnerRequest) (*emptypb.Empty, error)
	GetManagers(context.Context, *GetManagersRequest) (*GetManagersResponse, error)
	CanEditBusiness(context.Context, *CanEditBusinessRequest) (*CanEditBusinessResponse, error)
	// where current user is owner or admin
	GetOwnBusinesses(context.Context, *GetOwnBusinessesRequest) (*GetOwnBusinessesResponse, error)
	mustEmbedUnimplementedBusinessServer()
}

// UnimplementedBusinessServer must be embedded to have forward compatible implementations.
type UnimplementedBusinessServer struct {
}

func (UnimplementedBusinessServer) ApplyBusinessOwner(context.Context, *ApplyBusinessOwnerRequest) (*ApplyBusinessOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyBusinessOwner not implemented")
}
func (UnimplementedBusinessServer) VerifyBusinessOwner(context.Context, *VerifyBusinessOwnerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyBusinessOwner not implemented")
}
func (UnimplementedBusinessServer) AddBusinessAdmin(context.Context, *AddBusinessAdminRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBusinessAdmin not implemented")
}
func (UnimplementedBusinessServer) RemoveBusinessAdmin(context.Context, *RemoveBusinessAdminRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBusinessAdmin not implemented")
}
func (UnimplementedBusinessServer) SetCompanyOwner(context.Context, *SetBusinessOwnerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCompanyOwner not implemented")
}
func (UnimplementedBusinessServer) GetManagers(context.Context, *GetManagersRequest) (*GetManagersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManagers not implemented")
}
func (UnimplementedBusinessServer) CanEditBusiness(context.Context, *CanEditBusinessRequest) (*CanEditBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanEditBusiness not implemented")
}
func (UnimplementedBusinessServer) GetOwnBusinesses(context.Context, *GetOwnBusinessesRequest) (*GetOwnBusinessesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOwnBusinesses not implemented")
}
func (UnimplementedBusinessServer) mustEmbedUnimplementedBusinessServer() {}

// UnsafeBusinessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusinessServer will
// result in compilation errors.
type UnsafeBusinessServer interface {
	mustEmbedUnimplementedBusinessServer()
}

func RegisterBusinessServer(s grpc.ServiceRegistrar, srv BusinessServer) {
	s.RegisterService(&Business_ServiceDesc, srv)
}

func _Business_ApplyBusinessOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyBusinessOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).ApplyBusinessOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.Business/ApplyBusinessOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).ApplyBusinessOwner(ctx, req.(*ApplyBusinessOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_VerifyBusinessOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBusinessOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).VerifyBusinessOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.Business/VerifyBusinessOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).VerifyBusinessOwner(ctx, req.(*VerifyBusinessOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddBusinessAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBusinessAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddBusinessAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.Business/AddBusinessAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddBusinessAdmin(ctx, req.(*AddBusinessAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_RemoveBusinessAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBusinessAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).RemoveBusinessAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.Business/RemoveBusinessAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).RemoveBusinessAdmin(ctx, req.(*RemoveBusinessAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_SetCompanyOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBusinessOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).SetCompanyOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.Business/SetCompanyOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).SetCompanyOwner(ctx, req.(*SetBusinessOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetManagers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetManagers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.Business/GetManagers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetManagers(ctx, req.(*GetManagersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_CanEditBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanEditBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).CanEditBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.Business/CanEditBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).CanEditBusiness(ctx, req.(*CanEditBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetOwnBusinesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOwnBusinessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetOwnBusinesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/business.Business/GetOwnBusinesses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetOwnBusinesses(ctx, req.(*GetOwnBusinessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Business_ServiceDesc is the grpc.ServiceDesc for Business service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Business_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "business.Business",
	HandlerType: (*BusinessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyBusinessOwner",
			Handler:    _Business_ApplyBusinessOwner_Handler,
		},
		{
			MethodName: "VerifyBusinessOwner",
			Handler:    _Business_VerifyBusinessOwner_Handler,
		},
		{
			MethodName: "AddBusinessAdmin",
			Handler:    _Business_AddBusinessAdmin_Handler,
		},
		{
			MethodName: "RemoveBusinessAdmin",
			Handler:    _Business_RemoveBusinessAdmin_Handler,
		},
		{
			MethodName: "SetCompanyOwner",
			Handler:    _Business_SetCompanyOwner_Handler,
		},
		{
			MethodName: "GetManagers",
			Handler:    _Business_GetManagers_Handler,
		},
		{
			MethodName: "CanEditBusiness",
			Handler:    _Business_CanEditBusiness_Handler,
		},
		{
			MethodName: "GetOwnBusinesses",
			Handler:    _Business_GetOwnBusinesses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "business/business.proto",
}
