// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: opts/page.proto

package opts

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Opts with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Opts) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for FromId

	// no validation rules for Limit

	return nil
}

// OptsValidationError is the validation error returned by Opts.Validate if the
// designated constraints aren't met.
type OptsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OptsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OptsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OptsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OptsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OptsValidationError) ErrorName() string { return "OptsValidationError" }

// Error satisfies the builtin error interface
func (e OptsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOpts.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OptsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OptsValidationError{}

// Validate checks the field values on Page with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Page) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Skip

	// no validation rules for Limit

	return nil
}

// PageValidationError is the validation error returned by Page.Validate if the
// designated constraints aren't met.
type PageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageValidationError) ErrorName() string { return "PageValidationError" }

// Error satisfies the builtin error interface
func (e PageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageValidationError{}

// Validate checks the field values on SkipLimit with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *SkipLimit) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Skip

	// no validation rules for Limit

	return nil
}

// SkipLimitValidationError is the validation error returned by
// SkipLimit.Validate if the designated constraints aren't met.
type SkipLimitValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SkipLimitValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SkipLimitValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SkipLimitValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SkipLimitValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SkipLimitValidationError) ErrorName() string { return "SkipLimitValidationError" }

// Error satisfies the builtin error interface
func (e SkipLimitValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSkipLimit.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SkipLimitValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SkipLimitValidationError{}
